language: ruby
rvm:
  - 2.3
script: "bundle exec jekyll build"
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
notification:
  slack: $TRAVIS_SLACK_TOKEN
